### ISSUE TITLE
Question regarding mummichog 2 input format

### ISSUE THREAD

**Issue by MrTomRod** [shuzhao-li/mummichog#8]
Hi!

I would like to use `mummichog`, but have a question regarding the input format.

In https://shuzhao-li.github.io/mummichog.org/software.html, you specify that the file should be a tsv with 4 columns:
`mz`, `rtime`, `p-value` and `t-score`.

- The p-value has to be corrected for multiple testing, right?
- Reading through your notebooks, I decided to use the `Mann–Whitney U test` instead of the `t-test`. However, this test doesn't give a t-score. Can I use the `U statistic` or do I have to use the `t-test`?

**Comment by shuzhao-li** [comment]
You don't have to correct the p-values, as a pathway test is for patterns of top (ranked by significance) features relative to others.
"t-score" was used in examples, but it can be any statistical value. That column is only used for visual coloring now.

**Comment by song-sbio** [comment]
Hi, I would like to check if mummichog will be able to distinguish between positive mode and negative mode. I ran my LC-MS on negative mode, and i used the data to run mummichog. The output EmpiricalCompounds ion list has the format of M+H[1+] instead of  [M-H]-. Does that mean something was wrong and I should not trust the results? I tried to force the primary ions to be M-H[-] but it did not work.
mummichog -f /path/to.txt -c 0.05 -o output -z M-H[-]
